<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Approval.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NewLife.XCode" Version="12.2.2026.901" />
  </ItemGroup>

</Project>
